spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.41.43.95:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Yn123456..
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true